### PR TITLE
Code improvements and Visual Editor buttons

### PR DESCRIPTION
**Pull request by MattFryer**
Added button menu to the WordPress Visual Editor to make adding the shortcodes easier.

Improved code to register the CSS and js files but only enqueue them when the shortcode are added to a page/post. This is best practice for WordPress plugins to prevent loading unnecessary scripts on pages where they are not required.

Updated the Github and WordPress readme files.

I've had limited chance to test these improvements so I would suggest more testing before pushing the release out to WordPress.

### CODE REVIEW

**Comment by MattFryer** [comment]
Noticed I forgot to update the version number in the code files to match the readme files. qlik-sense.php and qlik-sense-shortcode-buttons.js both have now been updated to reflect new version v1.3.0

**Comment by yianni-ververis** [comment]
Matt, I merged everything to the wordpress plugins dir, but I do not see the badge getting the new version 1.3.0 even though it shows under 
https://wordpress.org/plugins/qlik-sense/

**Comment by MattFryer** [comment]
I’m guessing you might not have created a tag for the release. Wordpress repo has some weird rules. The trunk is not actually supposed to be where it takes the code from to push to users. That comes from the tags folder where you have to create a sub folder for the release (eg. “1.3.0”) then copy the code from the trunk into it. It only reads the header from the readme file in the trunk to get the stable release tag so it knows what folder from the tags to use. The rest of the readme and the code is then taken from the relevant tag sub folder. That way you can push changes to the trunk like you would on GitHub but they don’t get rolled out to users until you create the new tag release like creating a release in GitHub. What’s annoying is if you don’t follow the rules it seems to still mostly work but you get weird problems. It frustrated the hell out of me when I was first making the highlighting plugin. 

Even though I don’t have edit permissions, I should still be able to browse the Wordpress repo so let me do that when I get 5 mins and I’ll see if I’m able to spot the issue and come back to you.

**Comment by MattFryer** [comment]
I just checked and the badge is showing 1.3.0 now. Maybe a caching delay for shields.io?!

I’ll still check the Wordpress repo when I get chance.

**Comment by MattFryer** [comment]
As I thought, you have a stable tag defined in the readme that doesn't exist in the tags folder. Create a sub folder named "1.3.0" in the tags folder and copy the entire contents of the trunk folder into it. That should solve any issues. You'll need to do this each time you make a new release. I'd offer to do it for you but I haven't been able to find out how you could give my WordPress account access to the repo.

I have noticed there can be a delay ranging from a few minutes to several hours for changes I push to the repo to appear on the WordPress site and be offered to users. Apparently this is normal and is due to heavy loads on the scripts that process the readme and php header data. 

I've noticed a couple of mistakes in the readme and also that the settings aren't removed when the plugin is uninstalled so expect another pull request for those when I get the chance.

**Comment by MattFryer** [comment]
Hi Yianni
Just spotted that the js folder hasn't been committed to the WordPress plugin SVN either. Without it the visual editor buttons aren't working.

I've also noticed the plugin doesn't remove it's settings from the DB when uninstalled. Can look at this if needed.

Regards
Matt

**Comment by yianni-ververis** [comment]
Its there now! sorry for this. I committed without adding the folder into the trunk!!!

Thnx for catching early

**Pull request merged**
